name: TWRP CI
on:
  workflow_dispatch:
jobs:
  build:
    name: TWRP Build CI
    runs-on: ubuntu-22.04
    env:
      OEM: samsung
      DEVICE: loganreltexx
      BRANCH: twrp-6.0
    steps:
        - uses: actions/checkout@v7
        - name: Installing JDK 7 + Build Dependencies
          run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential ccache curl flex axel g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
            wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb && sudo dpkg -i libtinfo5_6.3-2_amd64.deb && rm -f libtinfo5_6.3-2_amd64.deb
            wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.3-2_amd64.deb && sudo dpkg -i libncurses5_6.3-2_amd64.deb && rm -f libncurses5_6.3-2_amd64.deb
            cd /usr/local/src
            sudo wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
            sudo tar xvf Python-2.7.18.tgz
            cd Python-2.7.18
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python2
            sudo ln -sf /usr/local/bin/python2.7 /usr/bin/python
        - name: Install OpenJDK
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: Syncing TWRP sources
          run: |
            mkdir ~/OFRP
            cd ~/OFRP
            mkdir ~/.bin
            curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
            python3 ~/.bin/repo init --depth=1 -u https://github.com/unlegacy-devices/fox-6.0_manifest.git -b fox_6.0
            python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
            git clone --depth=1 --branch cm-12.1 --single-branch https://github.com/notnoelchannel2/twrp_device_${{ env.OEM }}_${{ env.DEVICE }}.git device/${{ env.OEM }}/${{ env.DEVICE }}
            git clone --depth=1 --branch android-6.0.1_r32 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8
            git clone --depth=1 --branch cm-13.0 --single-branch https://github.com/MSM8930-Samsung/android_kernel_samsung_msm8930-common.git kernel/samsung/msm8930-common
        - name: Building TWRP
          run: |
            OLDPATH=$PATH
            OLDJAVAHOME=$JAVA_HOME
            export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
            export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
            cd ~/OFRP
            git clone https://github.com/TeamWin/android_device_qcom_common -b android-6.0 ~/OFRP/device/qcom/common
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL="C"
            export OF_FL_PATH1="/flashlight"
            export OF_MAINTAINER="NotNoelChannel"
            export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
            export OF_LEGACY_SHAR512=1
            export OF_DISABLE_KEYMASTER2=1
            lunch omni_${{ env.DEVICE }}-eng
            make -j$(nproc --all) recoveryimage
            export PATH=$OLDPATH
            export JAVA_HOME=$OLDJAVAHOME
        - name: Uploading TWRP builds
          uses: actions/upload-artifact@v5
          with:
            name: twrp
            path: /home/runner/OFRP/out/target/product/${{ env.DEVICE }}/recovery.*
